# 1B_3 Discretise
## Opening Data

In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

In [2]:
data_path = "./32130_2026A_88.csv"
adata = pd.read_csv(data_path)
# adata
adata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   source ID             3000 non-null   int64
 1   age                   3000 non-null   int64
 2   gender                3000 non-null   object
 3   marital_status        3000 non-null   object
 4   education_level       3000 non-null   object
 5   annual_income         3000 non-null   float64
 6   monthly_income        3000 non-null   float64
 7   employment_status     3000 non-null   object
 8   debt_to_income_ratio  3000 non-null   float64
 9   credit_score          3000 non-null   int64
 10  loan_amount           3000 non-null   float64
 11  loan_purpose          3000 non-null   object
 12  interest_rate         3000 non-null   float64
 13  loan_term             3000 non-null   int64
 14  installment           3000 non-null   float64
 15  num_of_open_accounts  3000 non-null   int64
 16  total_credit_limit    3000 non-null   float64
 17  current_balance       3000 non-null   float64
 18  delinquency_history   3000 non-null   int64
 19  num_of_delinquencies  3000 non-null   int64
 20  loan_paid_back        3000 non-null   int64
dtypes: float64(8), int64(8), object(5)
memory usage: 492.3+ KB

In [3]:
# Young (ages 21 and younger)
# Early Adulthood (ages 22--34).
# early Middle Age (ages 35--44),
# late Middle Age (ages 45--64), and
# Late Adulthood (ages 65 and older).
bins = [0, 21, 34, 44, 64, 120]
names = ['Young', 'Early Adulthood', 'early Middle Age', 'late Middle Age', 'Late Adulthood']

adata['age_categorized'] = pd.cut(adata['age'], bins, labels=names, include_lowest=True)


print(adata[['age', 'age_categorized']].sort_values('age'))
adata[['age', 'age_categorized']].sort_values('age').groupby('age_categorized').count()

      age age_categorized
2957   21           Young
42     21           Young
980    21           Young
979    21           Young
1676   21           Young
...   ...             ...
744    75  Late Adulthood
2429   75  Late Adulthood
2422   75  Late Adulthood
763    75  Late Adulthood
821    75  Late Adulthood

[3000 rows x 2 columns]

/tmp/ipykernel_2311/663916368.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  adata[['age', 'age_categorized']].sort_values('age').groupby('age_categorized').count()

                   age
age_categorized
Young               57
Early Adulthood    719
early Middle Age   593
late Middle Age   1038
Late Adulthood     593

## Export CSV

In [4]:
final=adata[['age', 'age_categorized']].sort_values('age')
final.to_csv('1B_3_Discretise.csv', index=False)
final

      age age_categorized
2957   21           Young
42     21           Young
980    21           Young
979    21           Young
1676   21           Young
...   ...             ...
744    75  Late Adulthood
2429   75  Late Adulthood
2422   75  Late Adulthood
763    75  Late Adulthood
821    75  Late Adulthood

[3000 rows x 2 columns]